name: PULL_REQUEST_CHECK

on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint
      - name: Unit testing
        run: npm test -- --coverage --watchAll=false
      - name: Try to compile
        run: npm run compile
      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_SHA: ${{ github.event.after }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
